### PR TITLE
Added typings, fixed import module error

### PR DESCRIPTION
**Pull request by hrvojepavlinovic**
- added typings
- switched import to require because of `SyntaxError: Cannot use import statement outside a module` error when using TS in main project
- version bump to 0.1.1

### CODE REVIEW

**Comment by timonmasberg** [comment]
@mandiwise lets get this merged? :=)

**Comment by thespacedeck** [comment]
Helooooo @mandiwise 
Please can we have this merged... :)
Thanks

**Comment by eastuto** [comment]
can this be merged pls @mandiwise ? 🙏

**Comment by mandiwise** [comment]
@hrvojepavlinovic @jakehewitt @Spolja @ijakab @burazBrat @timonmasberg @thespacedeck @eastuto 

Thanks for your patience with this. We have begun the process of making this TS-friendly (see #20) and that work has now been merged into `main`. 

Please keep in mind that this is meant to be a demonstration library, so the utils are meant for you to take and adapt for your project, rather than be installed as a critical dependency in your project.

Further PRs are welcome against the updated `main` branch and we should be able to attend to them faster than before now. Thanks for your interest in this solution!

**Comment by eastuto** [comment]
Thanks for merging this in @mandiwise . Just wondering has this been published to the latest npm ? Still getting these errors in the latest package

**Comment by mandiwise** [comment]
Hi @eastuto, the npm package that you're referring to wasn't published by Apollo. If you want to `npm i` this package for testing purposes, then you can do that directly from GitHub. But again, we caution that this is a demonstration library only and encourage you to take the code and adapt if your own use case in your projects.

**Pull request closed without merging**
